// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type FullUserProfile struct {
	IsAdmin        bool    `json:"isAdmin"`
	IsImpersonated bool    `json:"isImpersonated"`
	LoggedIn       bool    `json:"loggedIn"`
	OriginKaid     *string `json:"originKaid"`
	User           *User   `json:"user"`
}

type Permissions struct {
	AddEntries            bool `json:"add_entries"`
	AddUsers              bool `json:"add_users"`
	AssignEntryGroups     bool `json:"assign_entry_groups"`
	AssignEvaluatorGroups bool `json:"assign_evaluator_groups"`
	AssumeUserIdentities  bool `json:"assume_user_identities"`
	ChangeUserPasswords   bool `json:"change_user_passwords"`
	DeleteAllEvaluations  bool `json:"delete_all_evaluations"`
	DeleteAllTasks        bool `json:"delete_all_tasks"`
	DeleteContests        bool `json:"delete_contests"`
	DeleteEntries         bool `json:"delete_entries"`
	DeleteErrors          bool `json:"delete_errors"`
	DeleteKbContent       bool `json:"delete_kb_content"`
	EditAllEvaluations    bool `json:"edit_all_evaluations"`
	EditAllTasks          bool `json:"edit_all_tasks"`
	EditContests          bool `json:"edit_contests"`
	EditEntries           bool `json:"edit_entries"`
	EditKbContent         bool `json:"edit_kb_content"`
	EditUserProfiles      bool `json:"edit_user_profiles"`
	JudgeEntries          bool `json:"judge_entries"`
	ManageAnnouncements   bool `json:"manage_announcements"`
	ManageJudgingCriteria bool `json:"manage_judging_criteria"`
	ManageJudgingGroups   bool `json:"manage_judging_groups"`
	ManageWinners         bool `json:"manage_winners"`
	PublishKbContent      bool `json:"publish_kb_content"`
	ViewAdminStats        bool `json:"view_admin_stats"`
	ViewAllEvaluations    bool `json:"view_all_evaluations"`
	ViewAllTasks          bool `json:"view_all_tasks"`
	ViewAllUsers          bool `json:"view_all_users"`
	ViewErrors            bool `json:"view_errors"`
	ViewJudgingSettings   bool `json:"view_judging_settings"`
}

type User struct {
	ID            string       `json:"id"`
	Kaid          string       `json:"kaid"`
	Name          *string      `json:"name"`
	Nickname      *string      `json:"nickname"`
	Username      *string      `json:"username"`
	Email         *string      `json:"email"`
	AccountLocked *bool        `json:"accountLocked"`
	Permissions   *Permissions `json:"permissions"`
	IsAdmin       *bool        `json:"isAdmin"`
}
