name: Development Deployment

on:
  push:
    branches:
      - development
  workflow_dispatch:

jobs:
  publish_schema:
    runs-on: ubuntu-latest
    steps:
      - uses: danielsinclair/rover-publish@v1
        with:
          graph: Bema
          variant: development
          artifact: graph/schema.graphqls
        env:
          APOLLO_KEY: ${{ secrets.APOLLO_KEY }}
  deployment:
    runs-on: ubuntu-latest
    environment: bema-development
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}